
$(function() {
    // Populate using a JSON file
  WTF.init(
  {

    "heading": [
      ""
    ],

    "response": [
        "Already fucking seen one",
        "I saw that shit at MHACKs",
        "I saw that shit at HACKMIT",
        "Thats a fucking awful idea",
        "That wouldn't fucking succeed in the market",
        "That idea literally gave me cancer",
        "But is it the next yo",
        "Give me a-fucking-nother one",
        "Don't really give a fuck",
        "That doesn't make any fucking sense",
        "nobody would fund that",
        "are you high?",
        "are you drunk?",
        "go get some fucking sleep and then talk to me"
    ],

    "template": [
        "let's fucking @revolutionize @industry by @verb @buzzword",
        "How about we fucking @combination @company and @company? We'd be the next @company",
        "let's fucking make something like @company, but for @adjective @socialgroup",
        "we should fucking make @mobile app to @revolutionize @industry",
        "we should connect @adjective @socialgroup and @adjective @socialgroup with @buzzword"
    ],
    
    "adjective": [
        "sassy",
        "hipster",
        "busy",
        "well-connected",
        "international",
        "domestic",
        "cutting-edge",
        "obnoxious",
        "shy",
        "outgoing",
        "introverted",
        "social",
        "mature",
        "immature",
        "conservative",
        "liberal",
        "female",
        "male",
        "bisexual",
        "heterosexual",
        "homosexual",
        "boring",
        "exciting",
        "sweaty",
        "tired",
        "intense",
        "faithful",
        "atheist",
        "tall",
        "short",
        "self-conscious",
        "proud",
        "angry",
        "happy",
        "sad",
        "grumpy"
    ],

    "socialgroup": [
        "babies",
        "tweens",
        "adults",
        "highschoolers",
        "college students",
        "single moms",
        "single dads",
        "lonely housewives",
        "skateboarders",
        "preps",
        "jocks",
        "brogrammers",
        "programmers",
        "engineers",
        "scientists",
        "neighbors",
        "coworkers",
        "horny singles in your area",
        "europeans",
        "asians",
        "russians",
        "south africans",
        "germans",
        "true americans",
        "colonists",
        "truckers",
        "maintenance workers",
        "construction workers",
        "office drones",
        "start up billionaires",
        "starving artists",
        "starving programmers",
        "true believers",
        "hackers",
        "1337 h4x0rs",
        "kids",
        "orphans",
        "pokemon",
        "librarians",
        "consultants",
        "finance majors",
        "interns",
        "gamers",
        "business majors",
        "bloggers",
        "cashiers",
        "mobile app developers",
        "full stack developers",
        "students",
        "drug dealers"
    ],

    "company": [
        "facebook",
        "nextdoor",
        "medium",
        "twitter",
        "homejoy",
        "google",
        "yo",
        "snapchat",
        "apple",
        "tinder",
        "postmates",
        "github",
        "pebble",
        "airbnb",
        "lyft",
        "uber",
        "amazon",
        "groupon",
        "reddit",
        "groupme",
        "google+",
        "hipchat",
        "quora",
        "slack",
        "mailbox",
        "dropbox",
        "piazza",
        "eventbrite",
        "uber",
        "quora",
        "tumblr",
        "pinterest",
        "etsy",
        "venmo",
        "square",
        "netflix",
        "domino's",
        "papa john's",
        "chiptole",
        "nintendo",
    ],

    "revolutionize": [
        "revolutionize",
        "disrupt",
        "change the game of",
        "set the new standard for",
        "change the way people think of",
        "make you rethink",
    ],

    "industry": [
        "social media",
        "food delivery",
        "taxi service",
        "computing",
        "computers",
        "wearables",
        "environmentalism",
        "start-ups",
        "pizza delivery",
        "politics",
        "home cleaning",
        "search",
        "advertising",
        "marketing",
        "grocery shopping",
        "agriculture",
        "farming",
        "bitcoin",
        "soccer",
        "football",
        "basketball",
        "energy",
        "school",
        "education",
        "mobile computing",
        "manufacturing",
        "space travel",
        "time travel",
        "movie theatres",
        "apartment rentals",
        "video games",
        "meeting hot singles",
        "online shopping",
        "local business",
        "faxing",
        "messaging",
        "package delivery",
        "porn",
        "ereading",
    ],

    "combination": [
        "fuse",
        "take the best of",
        "seamlessly integrate",
    ],

    "verb": [
        "integrating",
        "crowd-sourcing",
        "adding"
    ],

    "buzzword": [
        "cloud computing",
        "the cloud",
        "machine learning",
        "crowd-sourcing",
        "open-source technology",
        "google glass",
        "wearables",
        "hackathons",
        "facebook",
        "social media",
        "twitter",
        "big data",
        "small data",
        "user experience",
        "a/b testing",
        "productivity",
        "rfid",
        "restful apis"
    ],

    "mobile": [
        "a blackberry",
        "an iOs",
        "an android",
        "a palm",
        "a flip phone",
        "an ipad",
        "an iphone",
        "a pebble",
        "a samsung gear",
    ]

  });
});
